export const MOCK_DATASETS = {
  plantel: {
    rows: [
      {
        id: "a1",
        numero: 101,
        brinco: "BR-1021",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a2",
        numero: 102,
        brinco: "BR-1022",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a3",
        numero: 103,
        brinco: "BR-1023",
        categoria: "Novilha",
        grupo: "Lote 2",
      },
      {
        id: "a4",
        numero: 104,
        brinco: "BR-1024",
        categoria: "Seca",
        grupo: "Lote 2",
      },
      {
        id: "a5",
        numero: 105,
        brinco: "BR-1025",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a6",
        numero: 106,
        brinco: "BR-1026",
        categoria: "Pré-parto",
        grupo: "Pré-parto",
      },
      {
        id: "a7",
        numero: 107,
        brinco: "BR-1027",
        categoria: "Novilha",
        grupo: "Lote 2",
      },
      {
        id: "a8",
        numero: 108,
        brinco: "BR-1028",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a9",
        numero: 109,
        brinco: "BR-1029",
        categoria: "Seca",
        grupo: "Lote 2",
      },
      {
        id: "a10",
        numero: 110,
        brinco: "BR-1030",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a11",
        numero: 111,
        brinco: "BR-1031",
        categoria: "Novilha",
        grupo: "Lote 2",
      },
      {
        id: "a12",
        numero: 112,
        brinco: "BR-1032",
        categoria: "Pré-parto",
        grupo: "Pré-parto",
      },
      {
        id: "a13",
        numero: 113,
        brinco: "BR-1033",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a14",
        numero: 114,
        brinco: "BR-1034",
        categoria: "Seca",
        grupo: "Lote 2",
      },
      {
        id: "a15",
        numero: 115,
        brinco: "BR-1035",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a16",
        numero: 116,
        brinco: "BR-1036",
        categoria: "Novilha",
        grupo: "Lote 2",
      },
      {
        id: "a17",
        numero: 117,
        brinco: "BR-1037",
        categoria: "Pré-parto",
        grupo: "Pré-parto",
      },
      {
        id: "a18",
        numero: 118,
        brinco: "BR-1038",
        categoria: "Vaca",
        grupo: "Lote 1",
      },
      {
        id: "a19",
        numero: 119,
        brinco: "BR-1039",
        categoria: "Seca",
        grupo: "Lote 2",
      },
      {
        id: "a20",
        numero: 120,
        brinco: "BR-1040",
        categoria: "Novilha",
        grupo: "Lote 2",
      },
    ],
  },
};
